FROM arm32v7/nginx:latest

COPY qemu-arm-static /usr/bin/

## Copy our default nginx config
COPY nginx/default.conf /etc/nginx/conf.d/

## Remove default nginx website
# RUN rm -rf /usr/share/nginx/html/*

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder
COPY dist/smarthome-gui/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]


